# Generated by Django 3.2.6 on 2021-08-09 02:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='images/avatars/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_plan',
            field=ckeditor.fields.RichTextField(default=None),
        ),
    ]
