# Generated by Django 3.2.6 on 2021-08-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20210809_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='images/avatars/%Y/%m'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('email', 'phone', 'avatar')},
        ),
    ]
