# Generated by Django 3.2.6 on 2021-08-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tour_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='static/images/avatars/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='static/images/avatars/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(upload_to='static/images/tours/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/images/avatars/%Y/%m'),
        ),
    ]
