# Generated by Django 3.2.6 on 2021-09-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
