# Generated by Django 3.2.6 on 2021-09-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_auto_20210914_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customers',
            field=models.ManyToManyField(blank=True, null=True, related_name='invoices', to='tours.Customer'),
        ),
    ]
