# Generated by Django 3.2.6 on 2021-09-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_auto_20210918_0922'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
    ]
