# Generated by Django 3.2.7 on 2021-09-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_auto_20210921_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payer',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
