# Generated by Django 3.2.7 on 2021-09-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_auto_20210921_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name_author',
        ),
    ]
