# Generated by Django 3.2.7 on 2021-09-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_remove_comment_name_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveSmallIntegerField(choices=[(0, 'adult'), (1, 'child')], default=0),
        ),
        migrations.DeleteModel(
            name='Age',
        ),
    ]
