# Generated by Django 3.2.7 on 2021-09-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_auto_20210926_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
