# Generated by Django 3.2.7 on 2021-10-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_blog_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'waiting'), (1, 'completed')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('blog', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('tour', 'user')},
        ),
    ]
