# Generated by Django 3.2.7 on 2021-10-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0020_auto_20211009_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='status',
            new_name='status_payment',
        ),
    ]
