# Generated by Django 3.2.7 on 2021-10-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0022_tour_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='banner',
            field=models.ImageField(default=None, upload_to='images/tour_banners/%Y/%m'),
        ),
    ]
