# Generated by Django 3.2.7 on 2021-10-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0025_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price_of_tour_child',
            field=models.FloatField(default=0),
        ),
    ]
